package com.hereliesaz.nhen

object BusinessData {
    val allBusinesses = listOf(
        // Restaurants
        Business("pucinella01", "Pucinella/Nightcap", "1032 St Charles Ave", "Restaurants", listOf("Vibrations")),
        Business("paladar511_01", "Paladar 511", "511 Marigny St", "Restaurants", listOf("Vibrations")),
        Business("royalsushi01", "Royal Sushi", "1913 Royal St", "Restaurants", listOf("Vibrations")),
        Business("thegoat01", "The Goat", "7824 Upperline St", "Restaurants", listOf("Esoteric", "Vibrations")),
        Business("holydiver01", "Holy Diver", "4422 Bienville St", "Restaurants", listOf("Esoteric", "Vibrations")),
        Business("poorboys01", "Poor Boys", "1328 St Bernard Ave", "Restaurants", listOf("Nocturnal", "Esoteric", "Vibrations")),
        Business("nodice01", "No Dice", "Location Varies", "Restaurants", listOf("Vibrations")),
        Business("dianxin01", "Dian Xin", "1218 Decatur St", "Restaurants", listOf("Quarter Bound")),
        Business("muriels01", "Muriel's", "801 Chartres St", "Restaurants", listOf("Quarter Bound")),
        Business("almas01", "Alma's", "800 Louisa St", "Restaurants", listOf("Quintessential")),
        Business("turkeywolf01", "Turkey & Wolf", "739 Jackson Ave", "Restaurants"),
        Business("lildizzys01", "Lil Dizzy’s", "1500 Esplanade Ave", "Restaurants", listOf("Vibrations")),
        Business("gajin01", "Gajin", "2800 Magazine St", "Restaurants"),
        Business("sweetsmeats01", "Sweetsmeats", "Location Varies", "Restaurants", listOf("Nocturnal", "Quarter Bound")),
        Business("vertimarte01", "Verti Marte", "1201 Royal St", "Restaurants", listOf("Nocturnal", "Quarter Bound")),
        Business("envie01", "Envie", "1241 Decatur St", "Restaurants", listOf("Quarter Bound")),
        Business("cooterbrowns01", "Cooter Brown’s", "509 S Carrollton Ave", "Restaurants"),
        Business("vampirecafe01", "Apothecary/Vampire Cafe", "801 Royal St", "Restaurants", listOf("Esoteric")),
        Business("igors01", "Igor’s", "2133 St Charles Ave", "Restaurants", listOf("Nocturnal")),
        Business("liuzzas01", "Louizza’s by the Track", "1518 N Lopez St", "Restaurants"),
        Business("pizzad01", "Pizza D", "617 Piety St", "Restaurants", listOf("Al Fresco")),
        Business("clovergrill01", "Clover Grill", "900 Bourbon St", "Restaurants", listOf("Nocturnal")),
        Business("perk01", "Perk", "3501 Holiday Dr", "Restaurants", listOf("Quarter Bound")),
        Business("peche01", "Peche", "800 Magazine St", "Restaurants"),
        Business("sneakypickle01", "Sneaky Pickle", "4401 Banks St", "Restaurants", listOf("Al Fresco")),
        Business("thejoint01", "The Joint", "701 Mazant St", "Restaurants", listOf("Quintessential")),
        Business("buffas01", "Buffa’s", "1001 Esplanade Ave", "Restaurants", listOf("Nocturnal")),
        Business("bacchanal01", "Bacchanal", "600 Poland Ave", "Restaurants", listOf("Al Fresco")),
        Business("besame01", "Besame", "Location Varies", "Restaurants"),
        Business("lebanoncafe01", "Lebanon Cafe", "1500 S Carrollton Ave", "Restaurants"),
        Business("luvi01", "LUVI", "5236 Tchoupitoulas St", "Restaurants"),
        Business("compierelupin01", "Compiere Lupin", "535 Tchoupitoulas St", "Restaurants"),
        Business("francollinis01", "Francollini’s", "1125 N Rampart St", "Restaurants"),
        Business("palmpine01", "Palm & Pine", "308 N Rampart St", "Restaurants"),
        Business("atchafalaya01", "Atchafalaya", "901 Louisiana Ave", "Restaurants", listOf("Al Fresco")),
        Business("butcher01", "Butcher", "930 Tchoupitoulas St", "Restaurants"),
        Business("flourmoon01", "Flour Moon", "4500 Tchoupitoulas St", "Restaurants", listOf("Quintessential")),
        Business("manchu01", "Manchu", "1413 N Claiborne Ave", "Restaurants"),
        Business("triangledeli01", "Triangle Deli", "1520 N Claiborne Ave", "Restaurants"),
        Business("gwfins01", "GW Fins", "808 Bienville St", "Restaurants"),
        
        // Bars
        Business("blackpenny01", "Black Penny", "700 N Rampart St", "Bars", listOf("Nocturnal", "Quarter Bound")),
        Business("santos01", "Santos", "1135 Decatur St", "Bars", listOf("Nocturnal", "Esoteric", "Quarter Bound")),
        Business("vicegraft01", "Vice & Graft", "524 S Rampart St", "Bars", listOf("Esoteric", "Quarter Bound")),
        Business("budrips01", "Bud Rips", "2200 Piety St", "Bars", listOf("Nocturnal", "Al Fresco")),
        Business("annas01", "Anna’s", "2601 Royal St", "Bars", listOf("Nocturnal", "Al Fresco")),
        Business("siberia01", "Siberia", "2227 St Claude Ave", "Bars", listOf("Esoteric", "Al Fresco")),
        Business("dungeon01", "The Dungeon", "738 Toulouse St", "Bars", listOf("Nocturnal", "Esoteric", "Quarter Bound")),
        Business("rambler01", "The Rambler", "3044 St Claude Ave", "Bars", listOf("Quarter Bound")),
        Business("pals01", "Pal’s", "949 N Rendon St", "Bars", listOf("Nocturnal")),
        Business("aunttikis01", "Aunt Tiki’s", "1207 Decatur St", "Bars", listOf("Nocturnal", "Quarter Bound")),
        Business("goldenlantern01", "Golden Lantern", "1239 Royal St", "Bars", listOf("Nocturnal", "Quarter Bound")),
        Business("goodfriends01", "Good Friends", "740 Dauphine St", "Bars", listOf("Quarter Bound")),
        Business("kajunkaroake01", "Kajun Karoake", "2256 St Claude Ave", "Bars", listOf("Vibrations")),
        Business("msmaes01", "Ms. Mae’s", "4336 Magazine St", "Bars", listOf("Nocturnal")),
        Business("mielsbrewery01", "Miel’s Brewery", "405 Sixth St", "Bars"),
        Business("abbey01", "The Abbey", "1123 Decatur St", "Bars", listOf("Nocturnal")),
        Business("spottedcat01", "Spotted Cat", "623 Frenchmen St", "Bars", listOf("Vibrations")),
        Business("shecomesinpeace01", "She Comes in Peace", "201 N Carrollton Ave", "Bars", listOf("Vibrations")),
        Business("dynamo01", "Dynamo", "Location Varies", "Bars", listOf("Vibrations")),
        Business("mrb01", "MRB", "515 St Philip St", "Bars", listOf("Quarter Bound")),
        Business("ricks01", "Rick’s", "315 Bourbon St", "Bars", listOf("Nocturnal", "Quarter Bound")),
        Business("barelylegal01", "Barely Legal", "432 Bourbon St", "Bars", listOf("Nocturnal", "Quarter Bound")),
        Business("railyard01", "Railyard", "2700 St Claude Ave", "Bars", listOf("Al Fresco")),
        Business("hanks01", "Hank’s", "235 N Rampart St", "Bars", listOf("Nocturnal")),
        Business("hooks01", "Hook’s", "1317 St Charles Ave", "Bars"),

        // Shops
        Business("nattyadams01", "Natty Adams", "620 St Peter St", "Shops", listOf("Esoteric", "Quarter Bound")),
        Business("gimme01", "Gimme", "4523 Magazine St", "Shops", listOf("Esoteric", "Quarter Bound")),
        Business("crazyplant01", "Crazy Plant Bae", "4893A Magazine St", "Shops", listOf("Esoteric")),
        Business("queentrinelisa01", "Queen Trina Lisa", "1432 St Charles Ave", "Shops", listOf("Quintessential")),
        Business("moongarden01", "Moon Garden", "2120 St Claude Ave", "Shops", listOf("Esoteric")),
        Business("hausofhoodoo01", "Haus of Hoodoo", "733 Bourbon St", "Shops", listOf("Esoteric")),
        Business("harolds01", "Harold’s", "1135 Press St", "Shops", listOf("Al Fresco")),
        Business("euclidrecords01", "Euclid Records", "3301 Chartres St", "Shops"),
        Business("octaviabooks01", "Octavia Books", "513 Octavia St", "Shops"),
        Business("sistersinchrist01", "Sisters in Christ", "5206 Magazine St", "Shops", listOf("Esoteric")),
        Business("hex01", "Hex", "1219 Decatur St", "Shops", listOf("Esoteric", "Quarter Bound")),
        Business("sassymagick01", "Sassy Magick", "3700 St Claude Ave", "Shops", listOf("Esoteric", "Quarter Bound")),
        Business("darkmatter01", "Dark Matter", "822 N Rampart St", "Shops", listOf("Esoteric", "Quarter Bound")),

        // Clubs
        Business("allwayslounge01", "Allways Lounge", "2240 St Claude Ave", "Clubs", listOf("Esoteric", "Vibrations")),
        Business("cabaret01", "Cabaret", "Location Varies", "Clubs", listOf("Nocturnal")),

        // Museums
        Business("pharmacymuseum01", "Pharmacy Museum", "514 Chartres St", "Museums", listOf("Esoteric", "Quarter Bound")),
        Business("storyvillemuseum01", "Storyville Museum", "124 Bourbon St", "Museums", listOf("Quarter Bound")),
        Business("voodoomuseum01", "Voodoo Museum", "724 Dumaine St", "Museums", listOf("Esoteric", "Quarter Bound")),
        Business("backstreet01", "Backstreet", "1531 St Philip St", "Museums"),
        Business("africanamerican01", "African American Heritage Museum", "1418 Governor Nicholls St", "Museums"),
        Business("burlesquemuseum01", "Burlesque Museum", "826 St Louis St", "Museums", listOf("Quarter Bound")),
        Business("sazerachouse01", "Sazerac House", "101 Magazine St", "Museums", listOf("Quarter Bound")),
        Business("studiob01", "Studio B", "2941 Royal St", "Museums")
    )
}
